// export const exampleDeviceEntries = [
//   { key: 'name', value: 'name' },
//   { key: 'type', value: 'type' },
//   { key: 'description', value: 'description' },
//   { key: 'additional_description', value: 'additional_description' },
//   { key: 'asset_url', value: 'asset_url' },
//   { key: 'url', value: 'url' },
//   { key: 'contact', value: 'contact' },
//   { key: 'visible', value: true },
//   { key: 'lat', value: '50.12' },
//   { key: 'lng', value: '30.54' },
//   { key: 'alt', value: '11111' },
//   { key: 'address_line_1', value: 'address_line_1' },
//   { key: 'address_line_2', value: 'address_line_2' },
//   { key: 'city', value: 'city' },
//   { key: 'postcode', value: 'postcode' },
//   { key: 'state', value: 'state' },
//   { key: 'country', value: 'country' },
//   { key: 'number', value: 'number' },
//   { key: 'floor', value: 'floor' },
//   { key: 'active', value: 'false' },
//   { key: 'connected', value: false },
//   { key: 'dapp', value: 'dapp' },
//   { key: 'owner', value: 'owner' },
//   { key: 'device_model', value: 'device_model' },
//   { key: 'custom_val1', value: 'val1' },
//   { key: 'custom_val2', value: 'val2' }
// ]

// export const exampleDeviceObject = {
//   name: 'name',
//   description: 'description',
//   type: 'type',
//   additionalDescription: 'additional_description',
//   assetUrl: 'asset_url',
//   url: 'url',
//   visible: true,
//   active: false,
//   connected: false,
//   dapp: 'dapp',
//   owner: 'owner',
//   deviceModel: 'device_model',
//   custom: { val2: 'val2', val1: 'val1' },
//   location: { lat: 50.12, lng: 30.54, alt: 11111 },
//   physicalAddress: {
//     addressLine1: 'address_line_1',
//     addressLine2: 'address_line_2',
//     city: 'city',
//     postcode: 'postcode',
//     state: 'state',
//     country: 'country',
//     number: 'number'
//   }
// }
